# Generated by Django 5.2.4 on 2025-12-11 10:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=12)),
                ('over_payed_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'place_category',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('is_financial_transaction', models.BooleanField(default=False)),
                ('place_category_id',
                 models.ForeignKey(db_column='place_category_id', on_delete=django.db.models.deletion.CASCADE,
                                   to='PaymentApp.placecategory'))
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('registration_number', models.CharField(max_length=13)),
                ('joined_at', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 19, 16, 18, 781998))),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(default='', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 19, 16, 18, 781998))),
                ('bank_id', models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.bank')),
                ('user_id', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.user')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_day', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.account')),
                ('account_number', models.ForeignKey(
                    db_column='account_number',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='PaymentApp.account',
                    to_field='number')
                 ),
                ('place_id', models.ForeignKey(db_column='place_id', default='', on_delete=django.db.models.deletion.CASCADE, related_name='a', to='PaymentApp.place')),
                ('user_id', models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.user')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 12, 11, 19, 16, 18, 784866))),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.user')),
            ],
            options={
                'db_table': 'alert',
            },
        ),
    ]
